<?php echo $this->form()->openTag($beerForm); ?>

<div class="form-group">
    <?php echo $this->formRow($beerForm->get('name')); ?>
</div>

<div class="form-group">
    <?php echo $this->formRow($beerForm->get('style')); ?>
</div>

<div class="form-group">
    <?php echo $this->formRow($beerForm->get('img')); ?>
</div>

<?php echo $this->formElement($beerForm->get('id')); ?>

<div class="form-buttons">
    <?php echo $this->formElement($beerForm->get('cancel')->setAttribute('onclick', "location.href='{$this->url('home')}'")); ?>

    <?php echo $this->formElement($beerForm->get('send')); ?>
</div>

<?php echo $this->form()->closeTag(); ?>
