<a href="<?php echo $this->url('create'); ?>" class="btn btn-default adicionar">
    <span class="glyphicon glyphicon-plus"></span> Adicionar cerveja
</a>
<table class="table table-striped">
<?php foreach ($beers as $beer): ?>
    <tr>
        <td class="col-xs-12 col-md-12"><?php echo $beer->name; ?></td>
        <td>
            <a href="<?php echo $this->url('update', ['id' => $beer->id]); ?>" class="btn btn-default">
                <span class="glyphicon glyphicon-edit"></span>
            </a>
        </td>
        <td>
            <a href="<?php echo $this->url('delete', ['id' => $beer->id]); ?>" class="btn btn-default">
                <span class="glyphicon glyphicon-trash"></span>
            </a>
        </td>
    </tr>
<?php endforeach; ?>
</table>
